Plain = {'dataset_out': 'TINY',
         'epochs': 100,
         'learning_rate': 0.1,
         'in_batch_size': 128,
         'seed': 1,
         'momentum': 0.9,
         'weight_decay': 0.0005,
         'augmentation': 'standard',
         'AA_cutout': True,
         'architecture_base': 'wrn',
         'layers': 40,
         'widen_factor': 2,
         'droprate': 0.3,
         'test': False,
         'out_data_number_limit':-1,
         }

OE = {'dataset_out': 'TINY',
      'epochs': 100,
      'learning_rate': 0.1,
      'in_batch_size': 128,
      'out_batch_size': 256,
      'seed': 1,
      'momentum': 0.9,
      'weight_decay': 0.0005,
      'augmentation': 'standard',
      'AA_cutout': True,
      'lamb': 0.5,
      'architecture_base': 'wrn',
      'layers': 40,
      'widen_factor': 2,
      'droprate': 0.3,
      'test': False,
      'out_data_number_limit':-1,
      }

BGC = {'dataset_out': 'TINY',
       'epochs': 100,
       'learning_rate': 0.1,
       'in_batch_size': 128,
       'out_batch_size': 256,
       'seed': 1,
       'momentum': 0.9,
       'weight_decay': 0.0005,
       'augmentation': 'standard',
       'AA_cutout': True,
       'lamb': 1.0,
       'architecture_base': 'wrn',
       'layers': 40,
       'widen_factor': 2,
       'droprate': 0.3,
       'test': False,
       'out_data_number_limit':-1,
       }

SharedCD = {'dataset_out': 'TINY',
            'epochs': 100,
            'learning_rate': 0.1,
            'in_batch_size': 128,
            'out_batch_size': 256,
            'seed': 1,
            'momentum': 0.9,
            'weight_decay': 0.0005,
            'augmentation': 'standard',
            'AA_cutout': True,
            'lamb': 1.0,
            'architecture_base': 'wrn',
            'layers': 40,
            'widen_factor': 2,
            'droprate': 0.3,
            'test': False,
            'out_data_number_limit':-1,
            }

SepD = {'dataset_out': 'TINY',
        'epochs': 100,
        'learning_rate': 0.1,
        'in_batch_size': 128,
        'out_batch_size': 256,
        'seed': 1,
        'momentum': 0.9,
        'weight_decay': 0.0005,
        'augmentation': 'standard',
        'AA_cutout': True,
        'lamb': 1.0,
        'architecture_base': 'wrn',
        'layers': 40,
        'widen_factor': 2,
        'droprate': 0.3,
        'test': False,
         'out_data_number_limit':-1,
        }

InMultiClassBin = {'dataset_out': 'TINY',
         'epochs': 100,
         'learning_rate': 0.1,
         'in_batch_size': 128,
         'seed': 1,
         'momentum': 0.9,
         'weight_decay': 0.0005,
         'augmentation': 'standard',
         'AA_cutout': True,
         'architecture_base': 'wrn',
         'layers': 40,
         'widen_factor': 2,
         'droprate': 0.3,
         'test': False,
         'out_data_number_limit':-1,
         }

SharedInMultiClassBin = {'dataset_out': 'TINY',
         'epochs': 100,
         'learning_rate': 0.1,
         'in_batch_size': 128,
         'seed': 1,
         'momentum': 0.9,
         'weight_decay': 0.0005,
         'augmentation': 'standard',
         'AA_cutout': True,
         'lamb': 1.0,
         'architecture_base': 'wrn',
         'layers': 40,
         'widen_factor': 2,
         'droprate': 0.3,
         'test': False,
         'out_data_number_limit':-1,
         }
